# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemocli < Formula
  desc "MnemoShare CLI - HIPAA-compliant secure file transfer"
  homepage "https://github.com/mnemoshare/mnemoshare"
  version "0.18.11"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MnemoShare/releases/releases/download/v0.18.11/mnemocli_0.18.11_darwin_amd64.tar.gz"
      sha256 "6323a20499b3b03a750a1724dc460150601d6684e1e14c2ea555eb394e6d2c07"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MnemoShare/releases/releases/download/v0.18.11/mnemocli_0.18.11_darwin_arm64.tar.gz"
      sha256 "cdd43486e54c48c6b4e1ad053e8c9502ef5d716765f555b580c600c361eae279"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MnemoShare/releases/releases/download/v0.18.11/mnemocli_0.18.11_linux_amd64.tar.gz"
      sha256 "d333a8eb5499cd8188bf3fefb7b6aa2d1c9fc631b4ab4e1fca706e52bc842aa2"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MnemoShare/releases/releases/download/v0.18.11/mnemocli_0.18.11_linux_arm64.tar.gz"
      sha256 "a9c411307f605a265523eb4e444c288ba8deb9fc2ca2950406e0ed5ffa44063d"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  test do
    system "#{bin}/mnemocli", "--version"
  end
end
