# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemocli < Formula
  desc "MnemoShare CLI - HIPAA-compliant secure file transfer"
  homepage "https://github.com/mnemoshare/mnemoshare"
  version "0.14.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.14.4/mnemocli_0.14.4_darwin_amd64.tar.gz"
      sha256 "64f7a023597db59eb0b29cd00183fc638cff3f689fdf6c72d02469350df6083c"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.14.4/mnemocli_0.14.4_darwin_arm64.tar.gz"
      sha256 "2212080cf2bb15fcea69a73bcd2a061f129cce657e625b9c54c710b0abed6452"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.14.4/mnemocli_0.14.4_linux_amd64.tar.gz"
      sha256 "977dc6a020e0af82da01cb70b6f79240fd113567d4fb3f16c00914e7215adf1a"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.14.4/mnemocli_0.14.4_linux_arm64.tar.gz"
      sha256 "47fb539b41bdf02a8f1ccfe4b6750fd726250bf4bd741e25ba4abd41090adc4c"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  test do
    system "#{bin}/mnemocli", "--version"
  end
end
