# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemocli < Formula
  desc "MnemoShare CLI - HIPAA-compliant secure file transfer"
  homepage "https://github.com/mnemoshare/mnemoshare"
  version "0.16.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.16.1/mnemocli_0.16.1_darwin_amd64.tar.gz"
      sha256 "45f599eda4a474e7df94cb5b1ff7e73fee8e8adfebf358cbac316e14abfc32a8"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.16.1/mnemocli_0.16.1_darwin_arm64.tar.gz"
      sha256 "3b0b439ef9ab993b2503e060c600fd3c84fc10ca9fb2c147986497dc6c99f46e"

      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.16.1/mnemocli_0.16.1_linux_amd64.tar.gz"
      sha256 "04ec5df13e0579379aef42669d452f5fc75b79e232a4e74cd0d197fe820e446b"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mnemoshare/mnemoshare/releases/download/v0.16.1/mnemocli_0.16.1_linux_arm64.tar.gz"
      sha256 "a873444686cdb67c579c56c10895c98a9320a9eff5f8c10cfceebdd45edae8f0"
      define_method(:install) do
        bin.install "mnemocli"
      end
    end
  end

  test do
    system "#{bin}/mnemocli", "--version"
  end
end
